# conda package dependencies
name: jbook
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  # - numba
  # - dask
  # - ruamel.yaml
  # - imageio
  - h5py
  - ipython
  - jupyter
  - matplotlib
  - openpyxl
  # -  pylint
  - jupyter-book
  - jupyterlab
  - jupytext
  # - tensorflow
