name: CI

on:
  push:
    # Build on tags that look like releases
    tags:
      - v*

jobs:
  publish-jupyter-book:
    name: Build Jupyter Book on Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: jbook-build
        environment-file: environment_build.yml
    - name: Build Jupyter Book
      run: |
        jupyter-book build .
    - name: Create artifact of the html output
      uses: actions/upload-artifact@v2
      with:
        name: JupyterBook
        path: _build/html
    - if: github.repository == 'ischoegl/ME-4933-adv-topics'
      name: Commit output to gh-pages branch
      run: |
        git clone https://github.com/ischoegl/ME-4933-adv-topics.git --branch gh-pages --single-branch gh-pages
        cp -r _build/html/* gh-pages/
        cd gh-pages
        # touch .nojekyll
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update book" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - if: github.repository == 'ischoegl/ME-4933-adv-topics'
      name: Push changes to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
